<?php

namespace SuperTokens\Session\Tests;

use SuperTokens\Session\Providers\SuperTokensServiceProvider;
use Orchestra\Testbench\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase {

    /**
     * @param \Illuminate\Foundation\Application $app
     * @return array
     */
    protected function getPackageProviders($app) {
        return [
            SuperTokensServiceProvider::class
        ];
    }

    protected function getPackageAliases($app) {
        return [
            'SuperTokens' => 'SuperTokens\Session\Facades\SuperTokens'
        ];
    }

    protected function getEnvironmentSetUp($app) {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub

        $app['config']->set('supertokens',  [
            'tokens' => [
                'accessToken' => [
                    'signingKey' => [
                        'dynamic' => env('AA', true),
                        'updateInterval' => env('BB', 24),
                        'get' => null,
                    ],
                    'validity' => env('DD', 3600),
                    'blacklisting' => env('EE', false),
                ],
                'refreshToken' => [
                    'validity' => env('FF', 2400),
                    'removalCronjobInterval' => env('GG'),
                    'renewTokenPath' => env('HH'),
                ],
            ]
        ]);
    }
}