version: 2
jobs:
  test:
    docker:
      - image: rishabhpoddar/laravel
    steps:
      - run: (cd / && ./runMySQL.sh)
      - run: mysql -u root --password=root -e "CREATE DATABASE auth_session;"
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  tagged-build:
    jobs:
      - test:
          filters:
            branches:
              only: 
                - dev
                - master