version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
  test:
    docker:
      - image: rishabhpoddar/laravel
    steps:
      - run: (cd / && ./runMySQL.sh)
      - run: mysql -u root --password=root -e "CREATE DATABASE auth_session;"
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          filters:
            branches:
              only: 
                - dev
                - master